// Google Signup
export const SIGNED_UP_WITH_GOOGLE = "SIGNED_UP_WITH_GOOGLE";
export const SIGNED_IN_WITH_GOOGLE = "SIGNED_IN_WITH_GOOGLE";
export const AUTH_WITH_GOOGLE = "AUTH_WITH_GOOGLE";
export const AUTH_WITH_GOOGLE_REQUESTED = "AUTH_WITH_GOOGLE_REQUESTED";
export const AUTH_WITH_GOOGLE_FAILED = "AUTH_WITH_GOOGLE_FAILED";
export const AUTH_WITH_GOOGLE_SUCCESSFUL = "AUTH_WITH_GOOGLE_SUCCESSFUL";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
// Sign out
export const SIGN_OUT = "SIGN_OUT";
