// Google Signup
export const SIGNED_UP_WITH_GOOGLE = "SIGNED_UP_WITH_GOOGLE";
export const SIGNED_IN_WITH_GOOGLE = "SIGNED_IN_WITH_GOOGLE";
export const AUTH_WITH_GOOGLE = "AUTH_WITH_GOOGLE";
export const AUTH_WITH_GOOGLE_REQUESTED = "AUTH_WITH_GOOGLE_REQUESTED";
export const AUTH_WITH_GOOGLE_FAILED = "AUTH_WITH_GOOGLE_FAILED";
export const AUTH_WITH_GOOGLE_SUCCESSFUL = "AUTH_WITH_GOOGLE_SUCCESSFUL";
// Sign oout
export const SIGN_OUT = "SIGN_OUT";
