const doctorActionTypes = {
  SET_CURRENT_DOCTOR_ID: 'SET_CURRENT_DOCTOR_ID',
  SET_DOCTOR_PATIENTS: 'SET_DOCTOR_PATIENTS',
  SET_CURRENT_PATIENT: 'SET_CURRENT_PATIENT'
};

export default doctorActionTypes;