const doctorActionTypes = {
  SET_CURRENT_DOCTOR_ID: 'SET_CURRENT_DOCTOR_ID',
  SET_DOCTOR_PATIENTS: 'SET_DOCTOR_PATIENTS',
  SET_CURRENT_PATIENT: 'SET_CURRENT_PATIENT',
  LOG_DOCTOR_IN: 'LOG_DOCTOR_IN',
  SET_DOCTOR_ACCESS_TOKEN: 'SET_DOCTOR_ACCESS_TOKEN',
  SET_DOCTOR_REFRESH_TOKEN: 'SET_DOCTOR_REFRESH_TOKEN',
};

export default doctorActionTypes;