const userActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UPDATE_USER_DETAILS: 'UPDATE_USER_DETAILS',
  SET_USER_GUIDES: 'SET_USER_GUIDES',
  ADD_PHONE_NUMBER: 'ADD_PHONE_NUMBER'
};

export default userActionTypes;
